spring:
    redis:
      jedis:
        ip: 10.120.121.16
        port: 6379
        auth: abcd-1234
    aop:
      proxy-target-class: true
    rabbitmq:
      host: 10.120.121.13
      port: 5672
      password: abcd-1234
 

ad:
 ldapurl: LDAP://lenovo.com
 port: 389
 context_factory: com.sun.jndi.ldap.LdapCtxFactory
 authentication: simple
 userhead: lenovo\\
 basicInfo: sAMAccountName,displayName,msExchExtensionAttribute16,telephoneNumber,mail
 extensionInfo: title,department,physicalDeliveryOfficeName,l,c,mobile,manager,msExchExtensionAttribute16,sAMAccountName,displayName,telephoneNumber

mongodb:
  username: 
  source: portal
  password: 
  serverAddress: 10.120.121.17
  port: 27017
pagesize: 20
